### ISSUE TITLE
[codacy-coverage-reporter] Add support for Xcode format

### ISSUE THREAD

**Issue by lolgab** [codacy/codacy-meta#122]
<p>Support Coverage for Swift</p>

**Comment by ljmf00** [comment]
I have done a quick investigation about this, and I found that most common coverage format for Swift is the Xcode report.

To generate coverage, you need to have an `.xcodeproj` and use `xcodebuild`. Inside the build output, the coverage is located in `Build/Logs/Test/`. As I searched using Xcode 7 you have the output directly on that folder in two formats: `.xccovreport` and `.xccovarchive`. On Xcode 10+ this are inside of `*.xcresult/*_Test/` folders.

This formats are not human readable, so we have two options to parse it:
- Using `xccov` to convert it to `.json` (human readable format) and then map it to codacy format.
- Parse `.xccovreport` using swift libraries. (e.g.: https://github.com/roman-dzieciol/swift-xcresult)

You can check this sample project and generate the coverage by yourself: `https://github.com/XCTEQ/XCCov-Demo`

Since I don't have a mac, and therefore, no Xcode, I'm not able to do that easily.

**Comment by mrfyda** [comment]
If we can't support the xcode format directly, we should at least document the how to convert it to one that is supported.

**Comment by josemiguelmelo** [comment]
This is solved by using [Slather](https://github.com/SlatherOrg/slather) to convert it to a format that is supported (https://github.com/codacy/codacy-coverage-reporter/pull/181)
