### ISSUE TITLE
update the version of pdepend to v2.7.0

### ISSUE THREAD

**Issue by codacy-support** [codacy/codacy-meta#260]
update the version of pdepend to v2.6.1<br><br><i>(created from <a href='https://codacy.zendesk.com/agent/tickets/9210'>Zendesk ticket #9210</a>)<br>gz#9210</i>

**Comment by DigiLive** [comment]
The update request was made because of a difference in the result of a Cyclomatic Complexity calculation. Codacy reports a complexity of 14, but according to me (and my local PHPMD 2.8.1snapshot201912271124) it's only 10.

Analysis of the branch I've committed today (10-03-2020) still reports a complexity of 14.
My local PHPMD 2.8.1snapshot201912271124 reports:
```shell
107 | VIOLATION | The method render() has a Cyclomatic Complexity of 10. The configured cyclomatic complexity threshold is 10.
```
Manual calculation:
```php
    public function render()
    {
        // 1
        foreach ($this->diff->getGroupedOpCodes() as $group) {
            // 2
            foreach ($group as $code) {
                // 3
                if (($tag == 'replace') && ($blockSizeOld == $blockSizeNew)) {
                    // 5
                }
                if ($tag == 'equal') {
                    // 6
                }
                if ($tag == 'replace' || $tag == 'delete') {
                    // 8
                }
                if ($tag == 'replace' || $tag == 'insert') {
                    // 10
                }
            }
        }
    }
```
