### ISSUE TITLE
Allow upload of multiple coverage reports for codacy-coverage-reporter-action

### ISSUE THREAD

**Issue by paulacodacy** [codacy/codacy-meta#362]

**Comment by franciscodua** [comment]
This problem should be fixed with this [PR](https://github.com/codacy/codacy-coverage-reporter-action/pull/14).
You can find the latest release [here](https://github.com/marketplace/actions/codacy-coverage-reporter).

Now you can just send a list of reports using a comma separated list of paths to reports
