### ISSUE TITLE
Rubocop reporting "Final newline missing" when it shouldn't

### ISSUE THREAD

**Issue by codacy-support** [codacy/codacy-meta#387]
Rubocop delivers "Final newline missing" for certain files, although the issue shouldn't be thrown since files seems to have correct content and when running the CLI or with a new same environment run in the UI, there's also no no "Final newline missing" being delivered.

Please check ticket internally for all necessary details.<br><br><i>(created from <a href='https://codacy.zendesk.com/agent/tickets/10485'>Zendesk ticket #10485</a>)<br>gz#10485</i>

**Comment by josemiguelmelo** [comment]
Apparently, this issue is being caused due to a problem in our cache that is not considering `\n` correctly for the caching key. This results into false positives for example in this particular case, which is related to the final newline missing. 

We are closing this issue as it is being tracked in another internal issue that intends to solve this caching problem.
