### ISSUE TITLE
Stylelint is failing for a repository using the UI patterns

### ISSUE THREAD

**Issue by codacy-support** [codacy/codacy-meta#410]
When going to the last commit of the repository, the "view logs" shows Stylelint failing, although there's no further information/log about this on the UI. 

The repository is using the UI Stylelint patterns.

Please check internal ticket for more informations.<br><br><i>(created from <a href='https://codacy.zendesk.com/agent/tickets/10786'>Zendesk ticket #10786</a>)<br>gz#10786</i>

**Comment by franciscodua** [comment]
Hi

What's causing this problem is the same that was described [here](https://github.com/codacy/codacy-meta/issues/417#issuecomment-645948894).

Quick summary, there's an issue being found on the last line of some of your files. In this case and because your repository is public, we ran the tool on a clone and found these issues
```json
{"file":"src/style/element-variables.scss","message":"Expected no more than 1 empty line (max-empty-lines)","patternId":"max-empty-lines","line":7}
{"file":"src/style/iconfont/iconfont.css","message":"Expected no more than 1 empty line (max-empty-lines)","patternId":"max-empty-lines","line":76}
```
And git blame only recognizes 6 and 75 lines, respectively (if you haven't checked the explanation you can check [here](https://github.com/codacy/codacy-meta/issues/417#issuecomment-645948894) to see why that's a problem).

As a workaround, you can delete the last newline in these files and your analysis should no longer fail.

This issue is already being worked on and we should have a fix for it soon.

**Comment by franciscodua** [comment]
The bug is already fixed. Re-analyzing your problematic commits will make the stylelint error disappear
