### ISSUE TITLE
Issues from "JSON sorting" and "JSON format", although not mentioned in the config file

### ISSUE THREAD

**Issue by codacy-support** [codacy/codacy-meta#415]
The file "package.json" delivers issues from rules "JSON sorting" and "JSON format", although they don't seem to be present in the config file ".eslintrc.js" and when running ESlint locally, the user doesn't receive any issues.

More info the internal ticket. Might be related with another open ticket: https://github.com/codacy/codacy-meta/issues/349
<br><br><i>(created from <a href='https://codacy.zendesk.com/agent/tickets/10913'>Zendesk ticket #10913</a>)<br>gz#10913</i><br><br><i>(related to <a href='https://codacy.zendesk.com/agent/tickets/10940'>Zendesk ticket #10940</a>)<br>gz#10940</i>

**Comment by franciscodua** [comment]
Hi

I'll post here the response I wrote in #349.

Probably, issues keep appearing, although not in the config file, because of the issue we opened [here](https://github.com/Bkucera/eslint-plugin-json-format/issues/14).
We added this ESLint plugin to our ESLint tool, but the plugin is a bit different from the others. And because of it, it doesn't follow the rules that are included in the configuration file. The issue we shared above should solve the problem when tackled.

If you want to ignore these patterns on your configuration file you can follow [these instructions](https://github.com/Bkucera/eslint-plugin-json-format#default-settings-eslintrc).
In sum, if your configuration file has this 👇 , it will ignore this pattern for every file:
```json
{
  "settings": {
    "json/ignore-files": ["**/*"]
  }
}
```

**Note:** It probably works when running ESLint locally, because you don't have the plugin installed.

**Comment by franciscodua** [comment]
I'll close this issue. 
If you're still experiencing the problem after trying the workaround, re-open it and let us know :smile:
