### ISSUE TITLE
TSlint failure when using UI patterns

### ISSUE THREAD

**Issue by paulacodacy** [codacy/codacy-meta#417]
No error message found in the UI "view logs" section, it only provides:
_An error occurred during this step. Please, retry your analysis or contact support._

<i>(related to <a href='https://codacy.zendesk.com/agent/tickets/10941'>Zendesk ticket #10941</a>)<br>gz#10941</i>

**Comment by josemiguelmelo** [comment]
Hi,

# Problem

In Unix, a file should end with a newline. For this reason, some tools consider the last newline as the end of file, thus considering the file has n-1 lines.
In the analysis process, we do `git blame -ls --root --line-porcelain -L<line>,<line> <filename>` for lines where issues were found.

TSLint is returning a _no-consecutive-blank-lines_ issue on the last line of the file. Because of it, we are doing git blame on the last line of the file. As git blame doesn't consider the last line, it throws a `fatal: file <filename> has only <number_of_lines> lines`.

# Workaround

As a workaround, you can remove the last line for the files that end with 2 empty lines, which should solve the issue given by TSLint.

# Solution

We are trying to figure out a good way to solve this problem.

**Comment by josemiguelmelo** [comment]
The problem is already fixed.
