### ISSUE TITLE
[CY-2475] Checkstyle error: cannot initialize module Header - Cannot set property 'headerFile' to ''

### ISSUE THREAD

**Issue by codacy-support** [codacy/codacy-meta#446]
More details in internal ticket<br><br><i>(created from <a href='https://codacy.zendesk.com/agent/tickets/11558'>Zendesk ticket #11558</a>)<br>gz#11558</i>

**Comment by josemiguelmelo** [comment]
Hi,

The 'headerFile' default value on Checkstyle is null.
When generating the configuration file, we were using empty string for null values on parameters. The 'headerFile' parameter does not allow empty string as value. To solve the problem, we are now only passing parameters with non null default values. 

The problem should be fixed in production.
