### ISSUE TITLE
PMD is failing to parse/process many files

### ISSUE THREAD

**Issue by codacy-support** [codacy/codacy-meta#447]
PMD is delivering error starting with:
- PMDException: Error while parsing
- PMDException: Error while processing
- RuntimeException:
and showing some pattern results in the log instead of in the UI:
- Unknown system function typeof()
- Prefix string has not been declared
- Unknown system function typeof()
- Prefix string has not been declared

More details in the internal ticket<br><br><i>(created from <a href='https://codacy.zendesk.com/agent/tickets/11558'>Zendesk ticket #11558</a>)<br>gz#11558</i>

**Comment by paulacodacy** [comment]
A previously created ticket seems to be also related to this one: https://github.com/codacy/codacy-meta/issues/422

**Comment by franciscodua** [comment]
The problem seems related to PMD's migration from XPath 1.0 to 2.0.

With the new version, booleans are represented with a `true()` or `false()` and not `'true'` or `'false'`. That's why the error message says `Cannot compare xs:boolean to xs:string`.

Example: The pattern `Missing Static Method In Non Instantiatable Class` had an XPath parameter with a default value of:
```
//ClassOrInterfaceDeclaration[@Nested='false']
[
  (
    ./ClassOrInterfaceBody/ClassOrInterfaceBodyDeclaration/ConstructorDeclaration
    and
    count(./ClassOrInterfaceBody/ClassOrInterfaceBodyDeclaration/ConstructorDeclaration) = count(./ClassOrInterfaceBody/ClassOrInterfaceBodyDeclaration/ConstructorDeclaration[@Private='true'])
  )
  and
  not(.//MethodDeclaration[@Static='true'])
  and
  not(.//FieldDeclaration[@Private='false'][@Static='true'])
  and
  not(.//ClassOrInterfaceDeclaration[@Nested='true']
           [@Public='true']
           [@Static='true']
           [not(./ClassOrInterfaceBody/ClassOrInterfaceBodyDeclaration/ConstructorDeclaration) or ./ClassOrInterfaceBody/ClassOrInterfaceBodyDeclaration/ConstructorDeclaration[@Public='true']]
           [./ClassOrInterfaceBody/ClassOrInterfaceBodyDeclaration/MethodDeclaration
                [@Public='true']
                [./ResultType/Type/ReferenceType/ClassOrInterfaceType
                    [@Image = //ClassOrInterfaceDeclaration[@Nested='false']/@Image]
                ]
            ]
        )
]
                
```

However, with [version 6.23](https://github.com/pmd/pmd/releases) users should start using the XPath version 2.0. And this comes with some changes, e.g., `'true' -> true()`.

You can find the tool's migration path as defined by PMD [here](https://pmd.github.io/latest/pmd_userdocs_extending_writing_xpath_rules.html#migrating-from-10-to-20).

As a fix, we recommend you go to your configuration and fix the XPath parameters for the rules that are failing. You can find the rules' XPath in their [documentation](https://pmd.github.io/latest/pmd_rules_java_errorprone.html#missingstaticmethodinnoninstantiatableclass) or in [the information we fetch from there](https://github.com/codacy/codacy-pmdjava/blob/master/src/main/resources/docs/patterns.json). These values can be copied to your Codacy UI configuration.

Example: For the rule I mentioned above `Missing Static Method In Non Instantiatable Class`, the new default value is:
```
//ClassOrInterfaceDeclaration[@Nested= false()]
[
  (
    (: at least one constructor :)
    ./ClassOrInterfaceBody/ClassOrInterfaceBodyDeclaration/ConstructorDeclaration
    and
    (: only private constructors :)count(./ClassOrInterfaceBody/ClassOrInterfaceBodyDeclaration/ConstructorDeclaration) = count(./ClassOrInterfaceBody/ClassOrInterfaceBodyDeclaration/ConstructorDeclaration[@Private= true()])
    and
    (: all constructors must not be annotated :)
    (every $x in $annotations satisfies
      not(./ClassOrInterfaceBody/ClassOrInterfaceBodyDeclaration/ConstructorDeclaration/
            ../Annotation/MarkerAnnotation/Name[pmd-java:typeIs($x)]))
  )
  and
  (: no static methods :)not(.//MethodDeclaration[@Static= true()])
  and
  (: no (public, package-private, protected) static fields :)not(.//FieldDeclaration[@Private= false()][@Static= true()])
  and
  (: no nested classes, that are public and static, and have no constructors at all or a public constructor :)
  (: and have a method returning the outer class type :)
  (: or the inner class extends the outer class :)not(.//ClassOrInterfaceDeclaration[@Nested= true()]
           [@Public= true()]
           [@Static= true()]
           [not(./ClassOrInterfaceBody/ClassOrInterfaceBodyDeclaration/ConstructorDeclaration) or ./ClassOrInterfaceBody/ClassOrInterfaceBodyDeclaration/ConstructorDeclaration[@Public= true()]]
           [(./ClassOrInterfaceBody/ClassOrInterfaceBodyDeclaration/MethodDeclaration
                [@Public= true()]
                [./ResultType/Type/ReferenceType/ClassOrInterfaceType
                    [@Image = //ClassOrInterfaceDeclaration[@Nested= false()]/@SimpleName]
                ]
            ) or (
                ./ExtendsList/ClassOrInterfaceType[@Image = //ClassOrInterfaceDeclaration[@Nested=false()]/@SimpleName]
            )]
        )
]
```

If this did not answer your questions let us know

**Comment by franciscodua** [comment]
I'll close this issue. Feel free to re-open it if you still have questions related to this problem
